---
http_interactions:
- request:
    method: post
    uri: https://circleci.com/api/v1.1/project/github/mtchavez/dotfiles/enable?circle-token=<TOKEN>
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
      Host:
      - circleci.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 14 Sep 2016 19:29:40 GMT
      Server:
      - nginx
      Set-Cookie:
      - ab_test_user_seed=0.3396850799247606;Expires=Thu, 14 Sep 2017 19:29:39 +0000;Path=/;Secure
      - ring-session=JioBvSt3bEs40leGd7LCRXIR%2FimuDeTc1RqyP51NoDTCc7TogbFuO3fxGo3cuFxrQDbXHLzgyv58AtpGa4%2F4qqhu4FdYPNTnzgwVRsLut59AG42g88PhukbjS%2BQro9BkZZaDeppb2Gy7dOhbfJpa8khy2nJjokD3OW39Y3EPloNGDwzmGeXTw4s3evBPifpxa0f5RgxPuJ2fmWr4xn3FOVOWQyWXPC3du4gkuN7dbKQ%3D--uj25OlvQBBZKDU30VBooOqNAvQeZrdjG0Aw%2BYTJxmJI%3D;Path=/;HttpOnly;Expires=Thu,
        14 Sep 2017 18:18:19 +0000;Max-Age=31536000;Secure
      Strict-Transport-Security:
      - max-age=15724800
      X-Circleci-Identity:
      - i-40bde5d0
      X-Circleci-Request-Id:
      - 86a010d0-a06a-4969-9aeb-cd662ac9be1a
      X-Circleci-Scopes:
      - ":all"
      - ":none"
      - ":read-settings"
      - ":status"
      - ":trigger-builds"
      - ":view-builds"
      - ":write-settings"
      X-Frame-Options:
      - DENY
      X-Route:
      - "/enable"
      Content-Length:
      - '509'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"irc_server":null,"scopes":["write-settings","view-builds","read-settings","trigger-builds","all","status","none"],"irc_keyword":null,"followed":false,"vcs-type":"github","aws":{"keypair":null},"slack_webhook_url":null,"flowdock_api_token":null,"parallel":1,"username":"mtchavez","campfire_room":null,"extra":"","branches":{},"slack_subdomain":null,"setup":"","campfire_subdomain":null,"slack_notify_prefs":null,"irc_password":null,"vcs_url":"https://github.com/mtchavez/dotfiles","default_branch":"master","hipchat_api_token":null,"irc_username":null,"language":null,"slack_channel_override":null,"hipchat_notify":null,"slack_api_token":null,"has_usable_key":true,"irc_notify_prefs":null,"campfire_token":null,"slack_channel":null,"feature_flags":{"trusty-beta":false,"osx":false,"set-github-status":true,"build-prs-only":false,"fleet":null,"build-fork-prs":false,"autocancel-builds":false,"junit":true,"oss":true},"campfire_notify_prefs":null,"hipchat_room":null,"heroku_deploy_user":null,"irc_channel":null,"oss":true,"reponame":"dotfiles","hipchat_notify_prefs":null,"compile":"","dependencies":"","test":"","ssh_keys":[]}'
    http_version: 
  recorded_at: Wed, 14 Sep 2016 19:31:20 GMT
- request:
    method: get
    uri: https://circleci.com/api/v1.1/project/github/mtchavez/dotfiles/checkout-key?circle-token=<TOKEN>
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
      Host:
      - circleci.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Origin:
      - "*"
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 14 Sep 2016 19:39:26 GMT
      Server:
      - nginx
      Set-Cookie:
      - ab_test_user_seed=0.3396850799247606;Expires=Thu, 14 Sep 2017 19:39:26 +0000;Path=/;Secure
      - ring-session=M8pMCbslBpEEXb6Rf5zSGa1u82wmE5QDLXSTpB%2B%2B92TnuaxlQIeZsZFfgOKUp9TjU3q%2FevYewmuj8ar94SYP4OiHzIWtsm5mcZDp0%2BtTM6WYg%2FIALudOm50LPPiA1%2FekfhEGGLRigArF0Tps%2F6X1LktJPoba5sPw2pUpVZctePt2zMEe9yFpPR1j6JeNJBzFKjVMSfdYB3rRy0kogywxEtfjRrH3tI3XycJ%2BLvEnbHU%3D--sMH%2FJ8gD%2FCDvkr384JrB2%2F0qfljQDkFVrQxJfw6hb0M%3D;Path=/;HttpOnly;Expires=Thu,
        14 Sep 2017 19:07:34 +0000;Max-Age=31536000;Secure
      Strict-Transport-Security:
      - max-age=15724800
      X-Circleci-Identity:
      - i-b7f8464f
      X-Circleci-Request-Id:
      - c369b248-d2cb-455d-a5f3-cc7d9ebdfb99
      X-Circleci-Scopes:
      - ":all"
      - ":none"
      - ":read-settings"
      - ":status"
      - ":trigger-builds"
      - ":view-builds"
      - ":write-settings"
      X-Frame-Options:
      - DENY
      X-Route:
      - "/checkout-key"
      Content-Length:
      - '478'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '[{"public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGu+6azAexpj2cxe8v1.1s2L9UckUPpJahXFJMoR8VIMHjwCS7642Q+0uxaTS8Ylf4Ms3A8iyWceruWmYBWpF2X2nbK5Gxj9wSzO4HvWJ24mdrbrbsepoEHHkAjDhrAQ8FEqA0UsYyrmZTFg35ZtsJYnP5qIDP/uO4gfWZRVJa5PkdWTEiMAY4+k4VQv7mzkHzDthklVdChIJcVW7TzPfeFifkUAQLEwO3ufd2dG5hkREAP28z5EdgoLYm/zT2ZzwpuHifSMm+agzT7U2Xg7ifU/pSoaHz3vb1pkLIV3yAA6bJLYcF8SsKJrJm+sw8NGkfCPLcZ+ujTK5YsplwJzCbC3
        \n","type":"deploy-key","fingerprint":"a4:17:20:b9:02:7f:19:93:84:b8:41:be:be:d3:29:b9","login":null,"preferred":true,"time":"2016-09-14T19:29:40.055Z"}]'
    http_version: 
  recorded_at: Wed, 14 Sep 2016 19:37:14 GMT
- request:
    method: get
    uri: https://circleci.com/api/v1.1/project/github/github/mtchavez/dotfiles/checkout-key?circle-token=<TOKEN>
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
      Host:
      - circleci.com
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Content-Type:
      - text/html; charset=utf-8
      Date:
      - Tue, 23 May 2017 20:04:45 GMT
      Server:
      - nginx
      Set-Cookie:
      - ring-session=sNmbsNZvz7zoLr4IrnLJ9f3TegQIua9Nposs1vJiwhqTBg2uWUSzmKwpdJeK%2BaTskZxESB2KJl9sbt6TwP141DvGczrDAO6yuh%2BFjRtP2CO4qaa9QcrFenFyCI8M%2Bn90PtdZv0dXXgSMLhFD9xyaKBMu5mEVQaYXvD9UCvI6bMDhUgokfxKX57LGi6am6kV4FXTn16dvn2sQ%2F7%2FQTXSOCbjrzp3sK2RiSBl%2FhPFl3wI%3D--2t1a6g5uLlilKJVVzftYFINs%2B6FEksBFNYWNpp%2BWjHg%3D;Path=/;HttpOnly;Expires=Wed,
        23 May 2018 19:53:23 +0000;Max-Age=31536000;Secure
      X-Circleci-Identity:
      - i-25464cbc
      X-Circleci-Request-Id:
      - 389a80b3-8967-4e50-a3fd-5c3fd65af55a
      X-Frame-Options:
      - DENY
      Content-Length:
      - '3560'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: |-
        <!DOCTYPE html>
        <html><head><title>Continuous Integration and Deployment</title><meta content="text/html; charset=utf-8" http-equiv="Content-Type"><meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"><meta content="width=device-width, initial-scale=1" name="viewport"><meta content="CircleCI" name="apple-mobile-web-app-title"><meta content="Hosted Continuous Integration for web applications. Set up your application for testing in one click, on the fastest testing platform on the internet." name="description"><link href="https://dmmj3mmt94rvw.cloudfront.net/favicon-undefined.ico" rel="icon" type="image/png"><link href="//dmmj3mmt94rvw.cloudfront.net/assets/css/app-b69cd148b2bd66451e8551af355597a3.css" rel="stylesheet" type="text/css"><script type="text/javascript">var circleEnvironment = "production";var circleHost = "i-25464cbc";var current_manifest_version_key = "frontend-releases/v3/367ad768072c853274f2ffa3ed098cc6265a03b8.json";var optimizelyUrl = '//dmmj3mmt94rvw.cloudfront.net/assets/js/hosted/optimizely-94c7bce52d627f8bcc7ed80e0c947108.js';var segmentUrl = '//dmmj3mmt94rvw.cloudfront.net/assets/js/hosted/segment-AbgkrgN4cbRhAVEwlzMkHbwvrXnxHh35-f0f5acd5bb0d8296bb6119d034d66958.js';var CSRFToken = 'TB_1Hf5gD7LLH01uxLw3nV_lcckys4Zabnz3BeuyoFOJAQi53ApPq_q2P2AHWLnl8pefQuuGeQOuC3KL';var OAuthCSRFToken = 'T5prQkL0Ah4wGhuni-InhSzE7P0SQujpTv7krnaUBHSwwieOQciUnez_XSavgCTkrgZwD0956A2hI2MO';</script><meta content="{&quot;assetsRoot&quot;:&quot;https://dmmj3mmt94rvw.cloudfront.net&quot;,&quot;enterprise&quot;:false,&quot;analytics_enabled&quot;:true,&quot;intercom_enabled&quot;:true,&quot;githubHttpEndpoint&quot;:&quot;https://github.com&quot;,&quot;support_email&quot;:&quot;support@circleci.com&quot;,&quot;pusher&quot;:{&quot;key&quot;:&quot;1cf6e0e755e419d2ac9a&quot;},&quot;user_session_settings&quot;:null,&quot;auth_protocol&quot;:&quot;https&quot;,&quot;current_user&quot;:null,&quot;status&quot;:404,&quot;logging_enabled&quot;:false,&quot;log_channels&quot;:false,&quot;instrument&quot;:false,&quot;bitbucketClientId&quot;:&quot;4DMqkNUJUMcdfnFtDU&quot;,&quot;githubClientId&quot;:&quot;78a2ba87f071c28e65bb&quot;,&quot;env&quot;:&quot;production&quot;,&quot;auth_host&quot;:null,&quot;flash&quot;:null,&quot;can_create_user&quot;:true,&quot;stripePublishableKey&quot;:&quot;pk_ZPBtv9wYtkUh6YwhwKRqL0ygAb0Q9&quot;,&quot;elevio_enabled&quot;:null}" id="aded3ec8-2f1a-40bf-b75a-2e1524c356f3" /><script type="text/javascript">var renderContext = JSON.parse(document.getElementById('aded3ec8-2f1a-40bf-b75a-2e1524c356f3').content);</script>
        <script type="text/javascript">
        !function(){var loadOptimizely=function(){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=optimizelyUrl;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};
        window.addEventListener('load', loadOptimizely, false);
        }();
        </script>


        <script type="text/javascript">
        !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=segmentUrl;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
        analytics.load();
        }}();
        </script>

        <script src="//d3dy5gmtp8yhk7.cloudfront.net/2.2/pusher.min.js" type="text/javascript"></script><script src="//dmmj3mmt94rvw.cloudfront.net/assets/js/hosted/intercom2-205572cbdda3126db3f800ef6ed1ef59.js" type="text/javascript"></script><meta content="{&quot;key&quot;:&quot;&quot;,&quot;email&quot;:null,&quot;name&quot;:null,&quot;custom&quot;:{&quot;organizations&quot;:[],&quot;in_beta_program&quot;:null,&quot;enrolled_betas&quot;:null,&quot;free&quot;:true}}" id="ea31124d-3da3-4a66-8c38-fcb10fb9f569" /><script type="text/javascript">var ldUser = JSON.parse(document.getElementById('ea31124d-3da3-4a66-8c38-fcb10fb9f569').content);</script><script crossorigin="anonymous" src="https://app.launchdarkly.com/snippet/features/562fbc5f169cf106f1000015.js" type="text/javascript"></script><script>!function(e,t){e.ldclient=e.ldclient||{},e.ldclient.q||(e.ldclient.q=[]),e.ldclient.push_event=function(t,n,i){e.ldclient.q.push({kind:t,key:n,data:i,url:e.location.href,creationDate:new Date})},e.ldclient.track=e.ldclient.send_event=function(t,n){if('string'!=typeof t)throw'Event key must be a string';e.ldclient.push_event('custom',t,n)},e.ldclient.set_user=e.ldclient.identify=e.ldclient.identify||function(t){e.ldclient.q.push({kind:'identify',key:t.key,user:t,creationDate:new Date}),e.ldclient.user=t};var n=e.document.createElement('script');n.type='text/javascript',n.async=!0,n.crossorigin='anonymous',n.src=t;var i=e.document.getElementsByTagName('script')[0];i.parentNode.insertBefore(n,i)}(this,'https://app.launchdarkly.com/snippet/events/v1/562fbc5f169cf106f1000015.js');</script><script>ldclient.identify(ldUser)</script>
        <script type="text/javascript">
        var _gaq = _gaq || [];

        if (window.circleEnvironment == "production") {
          _gaq.push(['_setAccount', "UA-25580673-1"]);
        } else {
          _gaq.push(['_setAccount', "UA-25580673-2"]);
        }

        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script');
          ga.type = 'text/javascript';
          ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(ga, s);
        })();
        </script>
        </head><noscript><h1>Hello there noscripter!</h1><p>CircleCI uses JavaScript pretty heavily to provide a good experience and to allow us to develop code a lot faster. We recognize that the tradeoff is that people using noscript get a worse experience, and we apologize for that.</p><p>So let us pitch you quickly on why you should enable JavaScript and view our site. CircleCI is <b>powerful, fast, and easy-to-use Continuous Integration and Deployment</b> for web applications.</p><p>CircleCI is easy to set up, incredibly fast, allows you to get your code to customers faster, and will even automatically parallelize your tests over many machines to get results to you faster. If that sounds useful, we'd encourage you to whitelist us in noscript and read about it yourself :)</p></noscript><body><div id="app"></div><script crossorigin="anonymous" src="//dmmj3mmt94rvw.cloudfront.net/assets/js/om-production-174fd8e203225bb71697127bbef09196.js" type="text/javascript"></script>
        <script type="text/javascript">
        function track_signup_conversion() {
          if (window.circleEnvironment == "production") {
            /* <![CDATA[ */
            var google_conversion_id = 1032131388;
            var google_conversion_label = "OYM1CK-vmW8QvKaU7AM";
            /* ]]> */
            trackConv(google_conversion_id,google_conversion_label);
          } else {
            console.log("Not in production: not recording conversion event");
          }
        }

        function trackConv(google_conversion_id,google_conversion_label) {
          var image = new Image(1,1);
          image.src = "https://www.googleadservices.com/pagead/conversion/"+google_conversion_id+"/?label="+google_conversion_label +"&script=0";
        }
        track_signup_conversion();

        // Google Code for Remarketing Tag
        if(window.circleEnvironment == "production"){
          var image = new Image(1,1);
          image.src = "https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1032131388/?value=0&amp;guid=ON&amp;script=0";
        }
        else{
          console.log('Not in production, not adding to retargeting list')
        }
        </script>
        <noscript>
          <div style="display:inline;">
          <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1032131388/?label=OYM1CK-vmW8QvKaU7AM&amp;guid=ON&amp;script=0"/>
          </div>
        </noscript>

        </body></html>
    http_version: 
  recorded_at: Tue, 23 May 2017 20:08:10 GMT
recorded_with: VCR 3.0.3
